In [25]:
import pandas as pd
import numpy as np
np.random.seed(0)

In [26]:
pwd

u'/Users/Bradley/Documents/Programming/Data_Vizualization_with_Python_and_JavaScript/ch_9'

In [27]:
ls

data/

In [28]:
cd ch_9

[Errno 2] No such file or directory: 'ch_9'
/Users/Bradley/Documents/Programming/Data_Vizualization_with_Python_and_JavaScript/ch_9

In [29]:
ls

data/

In [30]:
df = pd.read_json(open('data/nobel_winners.json'))

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1052 entries, 0 to 1051
Data columns (total 12 columns):
born_in           1052 non-null object
category          1052 non-null object
country           1052 non-null object
date_of_birth     1044 non-null object
date_of_death     1044 non-null object
gender            1040 non-null object
link              1052 non-null object
name              1052 non-null object
place_of_birth    1044 non-null object
place_of_death    1044 non-null object
text              1052 non-null object
year              1052 non-null int64
dtypes: int64(1), object(11)
memory usage: 106.8+ KB

In [32]:
df.describe()

,year
count,1052.000000
mean,1968.729087
std,33.155829
min,1809.000000
25%,1947.000000
50%,1975.000000
75%,1996.000000
max,2014.000000

In [33]:
df.describe(include=['object'])

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text
count,1052,1052,1052,1044,1044,1040,1052,1052,1044,1044,1052
unique,40,7,59,853,563,2,893,998,735,410,1043
top,,Physiology or Medicine,United States,9 May 1947,,male,http://en.wikipedia.org/wiki/Marie_Curie,Daniel Kahneman,,,"Edmond H. Fischer , born in China , Physiolog..."
freq,910,250,350,4,362,982,4,2,29,409,2

In [34]:
df.head()

,born_in,category,country,date_of_birth,date_of_death,gender,link,name,place_of_birth,place_of_death,text,year
0,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,César Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,Ivo Andric *,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,Vladimir Prelog *,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,Institut de Droit International,None,None,"Institut de Droit International , Peace, 1904",1904
4,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,Auguste Beernaert,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909

In [35]:
df.columns

Index([u'born_in', u'category', u'country', u'date_of_birth', u'date_of_death',
       u'gender', u'link', u'name', u'place_of_birth', u'place_of_death',
       u'text', u'year'],
      dtype='object')

In [36]:
df = df.set_index('name')

In [37]:
df.head(2)

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961

In [38]:
df.reset_index(inplace=True)

In [39]:
df.head(2)

,name,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961

In [40]:
bi_col = df.born_in
bi_col

0
1       Bosnia and Herzegovina
2       Bosnia and Herzegovina
3
4
5
6
7
8
9
10
11
12
13
14                     Belarus
15                     Belarus
16                     Belarus
17
18
19
20
21
22
23
24
25
26
27              Czech Republic
28              Czech Republic
29              Czech Republic
                 ...
1022
1023                   Austria
1024                   Austria
1025
1026
1027                   Austria
1028
1029
1030                   Austria
1031                   Austria
1032
1033
1034                   Austria
1035                 Australia
1036
1037
1038
1039                 Australia
1040
1041                 Australia
1042
1043
1044
1045
1046                 Australia
1047
1048
1049
1050
1051
Name: born_in, dtype: object

In [41]:
type(bi_col)

pandas.core.series.Series

In [42]:
df.iloc[0]

name                                                César Milstein
born_in
category                                    Physiology or Medicine
country                                                  Argentina
date_of_birth                                       8 October 1927
date_of_death                                        24 March 2002
gender                                                        male
link              http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein
place_of_birth                           Bahía Blanca ,  Argentina
place_of_death                                 Cambridge , England
text                 César Milstein , Physiology or Medicine, 1984
year                                                          1984
Name: 0, dtype: object

In [43]:
df.set_index('name', inplace=True)

In [44]:
df.loc['Albert Einstein']

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
Albert Einstein,,Physics,Switzerland,1879-03-14,1955-04-18,male,http://en.wikipedia.org/wiki/Albert_Einstein,"Ulm , Baden-Württemberg , German Empire","Princeton, New Jersey , U.S.","Albert Einstein , born in Germany , Physics, ...",1921
Albert Einstein,,Physics,Germany,1879-03-14,1955-04-18,male,http://en.wikipedia.org/wiki/Albert_Einstein,"Ulm , Baden-Württemberg , German Empire","Princeton, New Jersey , U.S.","Albert Einstein , Physics, 1921",1921

In [45]:
df[0:10]

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
Vladimir Prelog *,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
Institut de Droit International,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
Auguste Beernaert,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
Maurice Maeterlinck,,Literature,Belgium,29 August 1862,6 May 1949,male,http://en.wikipedia.org/wiki/Maurice_Maeterlinck,"Ghent , Belgium","Nice , France","Maurice Maeterlinck , Literature, 1911",1911
Henri La Fontaine,,Peace,Belgium,22 April 1854,14 May 1943,male,http://en.wikipedia.org/wiki/Henri_La_Fontaine,Brussels,Belgium,"Henri La Fontaine , Peace, 1913",1913
Jules Bordet,,Physiology or Medicine,Belgium,13 June 1870,6 April 1961,male,http://en.wikipedia.org/wiki/Jules_Bordet,"Soignies, Belgium",,"Jules Bordet , Physiology or Medicine, 1919",1919
Corneille Heymans,,Physiology or Medicine,Belgium,28 March 1892,18 July 1968,male,http://en.wikipedia.org/wiki/Corneille_Heymans,"Ghent , Flanders","Knokke , Flanders","Corneille Heymans , Physiology or Medicine, 1938",1938
Georges Pire,,Peace,Belgium,1910-02-10,1969-01-30,male,http://en.wikipedia.org/wiki/Georges_Pire,"Dinant , Belgium","Leuven , Belgium","Georges Pire , Peace, 1958",1958

In [46]:
df.reset_index(inplace=True)

In [47]:
df.loc[0]

name                                                César Milstein
born_in
category                                    Physiology or Medicine
country                                                  Argentina
date_of_birth                                       8 October 1927
date_of_death                                        24 March 2002
gender                                                        male
link              http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein
place_of_birth                           Bahía Blanca ,  Argentina
place_of_death                                 Cambridge , England
text                 César Milstein , Physiology or Medicine, 1984
year                                                          1984
Name: 0, dtype: object

In [48]:
df.set_index('name', inplace=True)

In [49]:
df.loc['Albert Einstein']

,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
name,,,,,,,,,,,
Albert Einstein,,Physics,Switzerland,1879-03-14,1955-04-18,male,http://en.wikipedia.org/wiki/Albert_Einstein,"Ulm , Baden-Württemberg , German Empire","Princeton, New Jersey , U.S.","Albert Einstein , born in Germany , Physics, ...",1921
Albert Einstein,,Physics,Germany,1879-03-14,1955-04-18,male,http://en.wikipedia.org/wiki/Albert_Einstein,"Ulm , Baden-Württemberg , German Empire","Princeton, New Jersey , U.S.","Albert Einstein , Physics, 1921",1921

In [50]:
df.reset_index(inplace=True)

In [51]:
df[0:10]

,name,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
0,César Milstein,,Physiology or Medicine,Argentina,8 October 1927,24 March 2002,male,http://en.wikipedia.org/wiki/C%C3%A9sar_Milstein,"Bahía Blanca , Argentina","Cambridge , England","César Milstein , Physiology or Medicine, 1984",1984
1,Ivo Andric *,Bosnia and Herzegovina,Literature,,9 October 1892,13 March 1975,male,http://en.wikipedia.org/wiki/Ivo_Andric,"Dolac (village near Travnik), Austria-Hungary ...","Belgrade, SR Serbia, SFR Yugoslavia (present-d...","Ivo Andric *, born in then Austria–Hungary ,...",1961
2,Vladimir Prelog *,Bosnia and Herzegovina,Chemistry,,"July 23, 1906",1998-01-07,male,http://en.wikipedia.org/wiki/Vladimir_Prelog,"Sarajevo , Bosnia and Herzegovina , then part...","Zürich , Switzerland","Vladimir Prelog *, born in then Austria–Hung...",1975
3,Institut de Droit International,,Peace,Belgium,None,None,None,http://en.wikipedia.org/wiki/Institut_de_Droit...,None,None,"Institut de Droit International , Peace, 1904",1904
4,Auguste Beernaert,,Peace,Belgium,26 July 1829,6 October 1912,male,http://en.wikipedia.org/wiki/Auguste_Marie_Fra...,"Ostend , Netherlands (now Belgium )","Lucerne , Switzerland","Auguste Beernaert , Peace, 1909",1909
5,Maurice Maeterlinck,,Literature,Belgium,29 August 1862,6 May 1949,male,http://en.wikipedia.org/wiki/Maurice_Maeterlinck,"Ghent , Belgium","Nice , France","Maurice Maeterlinck , Literature, 1911",1911
6,Henri La Fontaine,,Peace,Belgium,22 April 1854,14 May 1943,male,http://en.wikipedia.org/wiki/Henri_La_Fontaine,Brussels,Belgium,"Henri La Fontaine , Peace, 1913",1913
7,Jules Bordet,,Physiology or Medicine,Belgium,13 June 1870,6 April 1961,male,http://en.wikipedia.org/wiki/Jules_Bordet,"Soignies, Belgium",,"Jules Bordet , Physiology or Medicine, 1919",1919
8,Corneille Heymans,,Physiology or Medicine,Belgium,28 March 1892,18 July 1968,male,http://en.wikipedia.org/wiki/Corneille_Heymans,"Ghent , Flanders","Knokke , Flanders","Corneille Heymans , Physiology or Medicine, 1938",1938
9,Georges Pire,,Peace,Belgium,1910-02-10,1969-01-30,male,http://en.wikipedia.org/wiki/Georges_Pire,"Dinant , Belgium","Leuven , Belgium","Georges Pire , Peace, 1958",1958

In [53]:
df[-4:]

,name,born_in,category,country,date_of_birth,date_of_death,gender,link,place_of_birth,place_of_death,text,year
1048,Carlos Saavedra Lamas,,Peace,Argentina,"November 1, 1878","May 5, 1959",male,http://en.wikipedia.org/wiki/Carlos_Saavedra_L...,"Buenos Aires , Argentina","Buenos Aires, Argentina","Carlos Saavedra Lamas , Peace, 1936",1936
1049,Bernardo Houssay,,Physiology or Medicine,Argentina,1887-04-10,1971-09-21,male,http://en.wikipedia.org/wiki/Bernardo_Houssay,"Buenos Aires , Argentina","Buenos Aires , Argentina","Bernardo Houssay , Physiology or Medicine, 1947",1947
1050,Luis Federico Leloir,,Chemistry,Argentina,1906-9-6,1987-12-2,male,http://en.wikipedia.org/wiki/Luis_Federico_Leloir,"Paris , France","Buenos Aires , Argentina","Luis Federico Leloir , Chemistry, 1970",1970
1051,Adolfo Pérez Esquivel,,Peace,Argentina,"November 26, 1931",,male,http://en.wikipedia.org/wiki/Adolfo_P%C3%A9rez...,Buenos Aires,,"Adolfo Pérez Esquivel , Peace, 1980",1980

In [54]:
mask = df.year > 200